name: CI

on:
  workflow_dispatch:
    inputs:
      upload-wheel:
        type: boolean
        required: false
        default: false
        description: Upload wheel as an artifact
      pytest-flags:
        type: string
        required: false
        description: Additional flags to add to pytest
  pull_request:
  push:
    branches: [ main ]

permissions:
  security-events: write
  contents: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/step_test.yaml
    with:
      pytest-flags: ${{ inputs.pytest-flags }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    permissions:
      contents: read

  code-analysis:
    uses: ./.github/workflows/step_code-analysis.yml
    needs: [ tests ]
    secrets:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
    permissions:
      security-events: write
      contents: write
      checks: write
      pull-requests: write

  build-wheel:
    uses: ./.github/workflows/step_build-wheel.yaml
    needs: [ tests ]
    with:
      upload: ${{ inputs.upload-wheel || false }}
    permissions:
      contents: read
