name: CI

on:
  workflow_dispatch:
    inputs:
      upload-wheel:
        type: boolean
        required: false
        default: false
        description: Upload wheel as an artifact
      pytest-flags:
        type: string
        required: false
        description: Additional flags to add to pytest
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/step_pre-commit.yaml

  tests:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_test.yaml
    with:
      pytest-flags: ${{ inputs.pytest-flags }}

  code-analysis:
    uses: ./.github/workflows/step_code-analysis.yaml
    needs: [ tests ]
    secrets:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
    permissions:
      security-events: write
      contents: write
      checks: write
      pull-requests: write

  build-wheel:
    uses: ./.github/workflows/step_build-wheel.yaml
    needs: [ tests ]
    with:
      upload: ${{ inputs.upload-wheel || false }}

  pass:
    name: Pass
    needs: [ pre-commit, tests, build-wheel, code-analysis ]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: code-analysis
          jobs: ${{ toJSON(needs) }}
    if: always()
