name: Static code analysis
on:
  workflow_call:
    secrets:
      QODANA_TOKEN:
        required: false
        description: Qodana token

permissions:
  security-events: write
  contents: write
  checks: write
  pull-requests: write

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: pip
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Upload to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
